import type { Attestation } from "@/types/attestation";

const BASE_TIME = Date.now();

export const MOCK_ATTESTATIONS: Attestation[] = [
  {
    id: "att-001",
    agentId: "rwa",
    walletAddress: "7xKk...m3Pq",
    rating: 5,
    comment: "Explained tokenized treasury bonds better than any article I've read. Genuinely useful.",
    txSignature: "4kTnAvB7mXpR2qYsF9wLcDhE6jN3uKoGiZtWvP1eSx8dMrQfU5byCz0nHaIlOJ",
    blockHeight: 312847291,
    timestamp: BASE_TIME - 1000 * 60 * 30,
    sessionId: "sess-mock-001",
  },
  {
    id: "att-002",
    agentId: "rwa",
    walletAddress: "3mRv...p9Nw",
    rating: 5,
    comment: "Clear, concise, no fluff. Exactly what I needed to understand Solana RWA landscape.",
    txSignature: "2bJsYcK9nFqUwXiThPeL4aVrB6mDgEoCjZxHvN1uRtA8yWpMfS7dQkl3Iz0ObG",
    blockHeight: 312801045,
    timestamp: BASE_TIME - 1000 * 60 * 60 * 2,
    sessionId: "sess-mock-002",
  },
  {
    id: "att-003",
    agentId: "rwa",
    walletAddress: "9pLc...k7Xt",
    rating: 4,
    comment: "Very informative session on regulatory frameworks. Would have liked more depth on MiCA.",
    txSignature: "8nGwZtL2cPvRoKyAmX6bDqJ9eFhUsSi4jBMfYCx7NuWd3Tp1eVrl0HnQka5IoZ",
    blockHeight: 312754812,
    timestamp: BASE_TIME - 1000 * 60 * 60 * 5,
    sessionId: "sess-mock-003",
  },
  {
    id: "att-004",
    agentId: "defi",
    walletAddress: "5wNm...r2Qb",
    rating: 5,
    comment: "Finally understand how AMMs work. The Jupiter/Kamino comparison was spot on.",
    txSignature: "6vBxAoCn8rFuWqGsDhYk3jLpT2mEiXNzVtPbQ9cJsK7dUfR1eH4lMaZy0wIgOb",
    blockHeight: 312900123,
    timestamp: BASE_TIME - 1000 * 60 * 15,
    sessionId: "sess-mock-004",
  },
  {
    id: "att-005",
    agentId: "defi",
    walletAddress: "2hPt...v6Ys",
    rating: 5,
    comment: "Best explanation of yield farming risks I've encountered. Honest about the downsides.",
    txSignature: "9mKjRuZ4xTnDpQcBsHwL6aFoG2vCiEeYkN7bAVtP3fUMhW8qXrJ1SdIy0lObZg",
    blockHeight: 312856701,
    timestamp: BASE_TIME - 1000 * 60 * 60 * 3,
    sessionId: "sess-mock-005",
  },
  {
    id: "att-006",
    agentId: "defi",
    walletAddress: "8kXq...n4Wc",
    rating: 4,
    comment: "Good breakdown of staking mechanics. Could use more on liquid staking derivatives.",
    txSignature: "3sTpYhG7nMqBxLkCwDaJ5rVoZ9eFiPuNjH2bRtW6cUA1dXsKf4QmEy8Iz0lOgC",
    blockHeight: 312801990,
    timestamp: BASE_TIME - 1000 * 60 * 60 * 8,
    sessionId: "sess-mock-006",
  },
  {
    id: "att-007",
    agentId: "x402",
    walletAddress: "4rJw...b8Mn",
    rating: 5,
    comment: "Mind blown. HTTP 402 being dormant for 30 years and now x402 makes it real — incredible.",
    txSignature: "7cVnBsX3mGqRoKpAzLjY9dFhT2wEuWiZtNfCbP6eUH8kMsJ1rDxQa4Iy0lOgV",
    blockHeight: 312948201,
    timestamp: BASE_TIME - 1000 * 60 * 5,
    sessionId: "sess-mock-007",
  },
  {
    id: "att-008",
    agentId: "x402",
    walletAddress: "6fHs...d3Vk",
    rating: 5,
    comment: "Now I understand why autonomous AI payments needed a new protocol. This is the future.",
    txSignature: "1wLmZoK8nJtDpCxBsHrA9qFuG6vYiEePfN3bRsW7cUV2dTkMa5XeIy0lOgQh",
    blockHeight: 312891547,
    timestamp: BASE_TIME - 1000 * 60 * 60,
    sessionId: "sess-mock-008",
  },
  {
    id: "att-009",
    agentId: "x402",
    walletAddress: "1mQp...z5Rj",
    rating: 5,
    comment: "The agent economy section was eye-opening. Clear, practical, and genuinely exciting.",
    txSignature: "5dXoGpT7rNqBsLkCwMaJ4vFhZ9eAiPuNjH6bRtW2cUV8kEsK1XmDy0lIgOhZ",
    blockHeight: 312834129,
    timestamp: BASE_TIME - 1000 * 60 * 60 * 4,
    sessionId: "sess-mock-009",
  },
];

export function getAttestationsForAgent(agentId: string): Attestation[] {
  return MOCK_ATTESTATIONS.filter((a) => a.agentId === agentId).slice(0, 3);
}
